import {Inter} from 'next/font/google';
import {IProvider} from '../redux/iProvider';
import './globals.css';

const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <IProvider>{children}</IProvider>
      </body>
    </html>
  );
}
